back/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  namespace :api do
    namespace :v1 do
      resources :sessions, only: [:create]
      delete 'sessions' => 'sessions#destroy'
      resources :users, only: [:create]
    end
  end

  root "welcome#welcome"

  resources :users, except: [:show]
  get "users/confirming" => 'users#confirming', as: 'send'
  get 'users/email_confirm' => 'users#confirm'
  post "users/email_confirm" => 'users#email_confirm'
  get 'users/reconfirm' => 'users#reconfirm'
  
  resources :search, only: [:create]
  
  get "/session/new" => 'sessions#new'
  post "/session" => 'sessions#create'
  delete '/session' => 'sessions#destroy'
  
  resources :car_profiles do
    
    resources :comments, only: [:create, :destroy] do
      resources :likes, only: [:create, :destroy]
    end
    
    resources :favorites, only: [:index, :create, :destroy]
  end

  resources :welcome, only: [:welcome, :index]

  resources :accounts,  only: [:show]

end

back/app/models/car_profile.rb
class CarProfile < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favoraters, through: :favorites, source: :user

  # attaching images to car profiles
  has_one_attached :image

  validates :location, presence: true
end

back/app/controllers/car_profiles_controller.rb
class CarProfilesController < ApplicationController

    before_action :authenticate_user! , except: [:show]
    before_action :email_confirmed!, except: [:show]

    # creating form for new car profile
    def new
        @car = CarProfile.new
        @years = ['2010','2011','2012','2013','2014','2015']
    end

    # creating new car profile
    def create
        @car = CarProfile.new car_params
        # attaching the image to the car profile in active storage
        @car.image.attach params[:car_profile][:image]
        @car.user = current_user
        if @car.save
            redirect_to welcome_index_path
        else
            flash[:danger] = "Something went wrong!"
            render :new
        end
    end

    # showing the car profile
    def show
        @car = CarProfile.find params[:id]
        @comment = Comment.new
        @like = Like.new
        @favorite = Favorite.new
    end

    # create form for editing car profile
    def edit
        @car = CarProfile.find params[:id]
        # checking if the user is authorized to edit the car profile
        authorize! :edit, @car
        @years = ['2010','2011','2012','2013','2014','2015']
    end

    # updating car profile
    def update
        @car = CarProfile.find params[:id]
        # checking if the user is authorized to update the car profile
        authorize! :update, @car
        @car.update car_params
        if params[:car_profile][:image].present?
            @car.image.attach params[:car_profile][:image]
        end
        redirect_to car_profile_path(@car)
    end

    def destroy
        @car = CarProfile.find params[:id]
        # checking if the user is authorized to delete the car profile
        authorize! :destroy, @car
        @user = @car.user
        if @car.destroy
            flash[:warning] = "Car profile deleted successfully!"
            redirect_to account_path(@user)
        else
            flash[:danger] = "Something went wrong!"
            redirect_to account_path(@user)
        end
    end


    private

    def car_params
        params.require(:car_profile).permit(
            :model,
            :content,
            :year,
            :mileage,
            :location,
            :price,
            :image
        )
    end

end

back/app/helpers/car_profiles_helper.rb
module CarProfilesHelper
end

back/app/views/car_profiles/edit.erb
<div class='container mt-3' style='width:35rem' >
    <h2>Make a profile to rent your car:</h2>
    <%= form_for @car, method: :patch do |f| %>
        <div class='mt-2'>
            <%= f.label :model,"Model:", class:'form-label' %>
            <%= f.text_field :model, class:'form-control',placeholder:'Insert the model of your car' %>
        </div>
        <div class='mt-2'>
            <%= f.label :content,"Descriptions:", class:'form-label' %>
            <%= f.text_area :content, class:'form-control',placeholder:'Add you descriptions about the car' %>
        </div>
        <div class='mt-2'>
            <%= f.label :year,"Year:", class:'form-label' %>
            <%= f.select :year, options_for_select(@years, selected: f.object.year) %>
        </div>
        <div class='mt-2'>
            <%= f.label :mileage,"Mileage:", class:'form-label' %>
            <%= f.number_field :mileage, class:'form-control',placeholder:"Enter your car's mileage" %>
        </div>
        <div class='mt-2'>
            <%= f.label :location,"Location:", class:'form-label' %>
            <%= f.text_field :location, class:'form-control',placeholder:"Enter your location", required: true %>
        </div>
        <div class='mt-2'>
            <%= f.label :price,"Price:", class:'form-label' %>
            <%= f.number_field :price, class:'form-control',placeholder:"Insert car's daily rent price" %>
        </div>
        <div class='mt-2'>
            <%= f.label :image,"Picture:", class:'form-label' %>
            <%= f.file_field :image, class:'form-control', type:'file' %>
        </div>
        <%= f.submit "Submit", class:'mt-3 btn btn-outline-success' %>         
    <% end %>
</div>

back/app/views/car_profiles/new.erb
<div class='container mt-3' style='width:35rem' >
    <h2>Make a profile to rent your car:</h2>
    <%= form_for @car do |f| %>
        <div class='mt-2'>
            <%= f.label :model,"Model:", class:'form-label' %>
            <%= f.text_field :model, class:'form-control',placeholder:'Insert the model of your car', required: true %>
        </div>
        <div class='mt-2'>
            <%= f.label :content,"Descriptions:", class:'form-label' %>
            <%= f.text_area :content, class:'form-control',placeholder:'Add you descriptions about the car' %>
        </div>
        <div class='mt-2'>
            <%= f.label :year,"Year:", class:'form-label' %>
            <%= f.select :year, options_for_select(@years), required: true %>
        </div>
        <div class='mt-2'>
            <%= f.label :mileage,"Mileage:", class:'form-label' %>
            <%= f.number_field :mileage, class:'form-control',placeholder:"Enter your car's mileage", required: true %>
        </div>
        <div class='mt-2'>
            <%= f.label :location,"Location:", class:'form-label' %>
            <%= f.text_field :location, class:'form-control',placeholder:"Enter your location", required: true %>
        </div>
        <div class='mt-2'>
            <%= f.label :price,"Price:", class:'form-label' %>
            <%= f.number_field :price, class:'form-control',placeholder:"Insert car's daily rent price", required: true %>
        </div>
        <div class='mt-2'>
            <%= f.label :image,"Picture:", class:'form-label' %>
            <%= f.file_field :image, class:'form-control', type:'file' %>
        </div>
        <%= f.submit "Submit", class:'mt-3 btn btn-outline-success' %>         
    <% end %>
</div>

back/app/views/car_profiles/show.erb
<div class="container" style='width:60rem'>
    <div class="container d-flex justify-content-center">
        <div class='card w-70 mt-3' style='width:60rem'>
                <% if @car.image.present? %>
                    <%= image_tag @car.image,alt: 'No Image', class:'p-3' %>
                <% else %>
                    <%= image_tag "no_image.jpg", style:'width:17rem' %>
                <% end %>
            <div class="card-body">
                <p class="card-text">Descriptions: <%= @car.content %></p>
                <p class="card-text">Model: <%= @car.model.capitalize %></p>
                <p class="card-text">Year: <%= @car.year %></p>
                <p class="card-text">Mileage: <%= @car.mileage %> km</p>
                <p class="card-text">Price: <%= @car.price %>$ per day</p>
                <p class="card-text">Location: <%= @car.location %></p>
                <p class="card-text">Owner's contact info: <%= @car.user.email %></p>
                <p class="card-text">This advertise has created by <%= @car.user.full_name.capitalize %>, <%= time_ago_in_words(@car.created_at) %> ago.</p>
                <% if user_signed_in? %>
                    <div class='d-flex justify-content-end'>
                        <% if (favorite = user_favorited_car(@car)) %>
                            <%= button_to "Remove from Favorites", car_profile_favorite_path(@car, favorite), class:'btn btn-warning', method: :delete %>
                        <% else %>
                            <%= button_to "Add to Favorites", car_profile_favorites_path(@car), class:'btn btn-info' %>
                        <% end %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
    <h2 class='mt-5 text-primary'>Comments:</h2>
    <div class='p-3'>
        <% if @car.comments == [] %>
            <p>There is no comment for this add.</p>
        <% else %>
        <ul class='list-group list-group'>
            <% @car.comments.each do |c| %>
                <li class="list-group-item">
                    <p class='fs-4'><%= c.content %></p>
                    <div class='d-flex align-items-center'>
                    <small><%= "This comment has created by #{c.user.full_name.truncate(10)} #{time_ago_in_words(c.created_at)} ago."%></small>
                    <% if can?(:destroy,c) %>
                        <small><%= button_to "Delete Comment", car_profile_comment_path(@car,c), class:"btn text-decoration-none text-danger", method: :delete %></small>
                    <% end %>
                    </div>
                    <div class="d-flex justify-content-between mt-1">
                        <p class="m-2">Likes: <%= c.likers.count %></p>
                        <% if user_signed_in? %>
                            <% if (like = user_liked_comment(c)) %>
                                <% if can? :destroy,like %>
                                    <%= button_to "Unlike", car_profile_comment_like_path(@car, c, like), method: :delete, class:"btn btn-danger"%>
                                <% end %>
                            <% else %>
                                    <%= button_to "Like", car_profile_comment_likes_path(@car, c), method: :post, class:'btn btn-success' %>
                            <% end %>
                        <% end %>
                    </div>
                </li>
            <% end %>
        <ul>
        <% end %>
    </div>
    <div class=' w-50 mb-5 p-3'>
        <%= form_for [@car, @comment] do %>
            <%= label_tag :content, "Leave Your Comment:", class:'form-label' %>
            <%= text_area_tag :content, nil, class:'form-control' %>
            <%= submit_tag "Submit Comment", class:'btn btn-success mt-3' %>
        <% end %>
    </div>
</div>