back/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  namespace :api do
    namespace :v1 do
      resources :sessions, only: [:create]
      delete 'sessions' => 'sessions#destroy'
      resources :users, only: [:create]
    end
  end

  root "welcome#welcome"

  resources :users, except: [:show]
  get "users/confirming" => 'users#confirming', as: 'send'
  get 'users/email_confirm' => 'users#confirm'
  post "users/email_confirm" => 'users#email_confirm'
  get 'users/reconfirm' => 'users#reconfirm'
  
  resources :search, only: [:create]
  
  get "/session/new" => 'sessions#new'
  post "/session" => 'sessions#create'
  delete '/session' => 'sessions#destroy'
  
  resources :car_profiles do
    
    resources :comments, only: [:create, :destroy] do
      resources :likes, only: [:create, :destroy]
    end
    
    resources :favorites, only: [:index, :create, :destroy]
  end

  resources :welcome, only: [:welcome, :index]

  resources :accounts,  only: [:show]

end

back/app/models/user.rb
class User < ApplicationRecord

    has_secure_password

    has_many :CarProfiles, dependent: :destroy

    has_many :comments, dependent: :destroy

    has_many :favorites, dependent: :destroy
    has_many :favorated_cars, through: :favorites, source: :car_profile

    has_many :likes, dependent: :destroy
    has_many :liked_comments, through: :likes, source: :user

    validates :first_name, presence: true
    validates :last_name, presence: true

    # password validating, shoudld be valid and in an email format
    validates :email, uniqueness:{case_sensitive: false} , format: { with:/^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i, multiline: true }

    # the password should have at least 8 characters
    validates :password, length: { minimum: 8, message: 'Password needs to have at least 8 characters.' }
    
    # the passord shoulf have at least one number and one uppercase letter
    validates_format_of :password, with: /\A(?=.*[A-Z])(?=.*[1-9])/, message: 'Password needs to have at least one number and one uppercase letter in its body.' 

    # creating and saving the user's full name while creating the user account
    def full_name
        first_name.capitalize + ' ' + last_name.capitalize
    end

end

back/app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController

    before_action :authenticate_user!, except: [:new, :create]

    def confirm
        # generating a random code
        @confirm_code = SecureRandom.hex(3)
        @user = current_user
        # saving the code in the database
        @user.confirmed_email_code = @confirm_code
        if @user.save(validate:false)
            # sending the email regarding the confirmation code
            CreateAccountMailer.email_confirmation(@user, @confirm_code).deliver_now
        else
            flash[:danger] = 'Something wnet wrong, Please try again.'
            redirect_to send_path
        end
    end

    # confirming the email address process
    def email_confirm
        @user = current_user
        if @user.confirmed_email_code == params[:confirm]
            # updating the confirmed email status
            @user.confirmed_email = true
            if @user.save(validate: false)
                flash[:success] = "Your email address has been confirmed successfully!"
                redirect_to root_path
            else
                flash[:danger] = "Something went wrong, try again!"
                redirect_to usrs_reconfirm_path
            end
        else
            flash[:warning] = "The code you have entered is wrong! Please try again."
            redirect_to users_reconfirm_path
        end
    end

    # creating new user account
    def create
        @user = User.new user_params
        # set the confirmed email status to false by default
        @user.confirmed_email = false
        if @user.save
            # # sending an email to the user to aske them to confirm their email address
            # CreateAccountMailer.notify_new_user(@user).deliver_now
            render json: { message: "Account created successfully!", status: 200 }
        else 
            render json: { message: @user.errors.full_messages, status: 401 }
        end

    end

    def edit
        @user = User.find params[:id]
        authorize! :edit, @user
    end

    # updating user account
    def update
        @user = User.find params[:id]
        new_email = params[:user][:email]
        old_email = @user.email
        authorize! :update, @user
        @user.first_name = params[:user][:first_name]
        @user.last_name = params[:user][:last_name]
        @user.email = params[:user][:email]
        # cheking if the user has changed their email address
        if new_email != old_email
            # if the user has changed their email address, set the confirmed email status to false and they need to confirm the new email address
            @user.confirmed_email = false
        end
        if @user.save(validate: false)
            flash[:warning] = "You have updated your account seccessfully!"
            redirect_to account_path(@user)
        else
            flash[:danger] = "Something went wrong, try again!"
            redirect_to edit_user_path(@user)
        end
    end

    # deleting user account
    def destroy
        @user = User.find params[:id]
        authorize! :destroy, @user
        if @user.destroy
            flash[:danger] = 'Your account was deleted successfully!'
            redirect_to root_path
        else
            flash[:warning] = "Something wetn wrong!"
            redirect_to account_path(@user)
        end
    end

    private

    def user_params
        params.require(:user).permit(
            :first_name,
            :last_name,
            :email,
            :password,
            :password_confirmation,
            :admin,
            :confirmed_email
        )
    end
    
end

back/app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :authenticate_user!, except: [:new, :create]

    def new
        @user = User.new
    end

    def confirming

    end

    def confirm
        # generating a random code
        @confirm_code = SecureRandom.hex(3)
        @user = current_user
        # saving the code in the database
        @user.confirmed_email_code = @confirm_code
        if @user.save(validate:false)
            # sending the email regarding the confirmation code
            CreateAccountMailer.email_confirmation(@user, @confirm_code).deliver_now
        else
            flash[:danger] = 'Something wnet wrong, Please try again.'
            redirect_to send_path
        end
    end

    # the page where the user ask to resent the confirmation code to their email
    def reconfirm

    end

    # confirming the email address process
    def email_confirm
        @user = current_user
        if @user.confirmed_email_code == params[:confirm]
            # updating the confirmed email status
            @user.confirmed_email = true
            if @user.save(validate: false)
                flash[:success] = "Your email address has been confirmed successfully!"
                redirect_to root_path
            else
                flash[:danger] = "Something went wrong, try again!"
                redirect_to usrs_reconfirm_path
            end
        else
            flash[:warning] = "The code you have entered is wrong! Please try again."
            redirect_to users_reconfirm_path
        end
    end

    # creating new user account
    def create
        @user = User.new user_params
        # set the confirmed email status to false by default
        @user.confirmed_email = false
        if @user.save
            # sending an email to the user to aske them to confirm their email address
            CreateAccountMailer.notify_new_user(@user).deliver_now
            flash[:success] = "Your Accout has been created successfully!"
            redirect_to session_new_path
        end
    end

    def edit
        @user = User.find params[:id]
        authorize! :edit, @user
    end

    # updating user account
    def update
        @user = User.find params[:id]
        new_email = params[:user][:email]
        old_email = @user.email
        authorize! :update, @user
        @user.first_name = params[:user][:first_name]
        @user.last_name = params[:user][:last_name]
        @user.email = params[:user][:email]
        # cheking if the user has changed their email address
        if new_email != old_email
            # if the user has changed their email address, set the confirmed email status to false and they need to confirm the new email address
            @user.confirmed_email = false
        end
        if @user.save(validate: false)
            flash[:warning] = "You have updated your account seccessfully!"
            redirect_to account_path(@user)
        else
            flash[:danger] = "Something went wrong, try again!"
            redirect_to edit_user_path(@user)
        end
    end

    # deleting user account
    def destroy
        @user = User.find params[:id]
        authorize! :destroy, @user
        if @user.destroy
            flash[:danger] = 'Your account was deleted successfully!'
            redirect_to root_path
        else
            flash[:warning] = "Something wetn wrong!"
            redirect_to account_path(@user)
        end
    end

    private

    def user_params
        params.require(:user).permit(
            :first_name,
            :last_name,
            :email,
            :password,
            :password_confirmation,
            :admin,
            :confirmed_email
        )
    end

end

back/app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

back/app/helpers/users_helper.rb
module UsersHelper
end

back/app/views/users/confirm.erb
<div class='container mt-4' style='width:45rem'>
    <h2>Email Confirmation:</h2>
    <p>In this section, we have sent an email to "<%= current_user.email %>" email address, for finalizing your account creation, you need to enter the CONFIRMATION code in the below form:</p>
    <%= form_tag users_email_confirm_path do %>
        <div>
            <%= label_tag :confirm, "Code:", class:'form-label' %>
            <%= text_field_tag :confirm, nil, class:'form-control', required: true %>
        </div>
        <%= submit_tag "Submit", class:'btn btn-primary mt-3' %>
    <% end %>
    <h4 class="mt-5">You havn't received any code in your email address, click <%= link_to "here", users_email_confirm_path %> to resent the code.</h4>
</div>

back/app/views/users/confirming.erb
<div class='container mt-4' style='width:45rem'>
    <h2>Dear <%= current_user.full_name %></h2>
    <p>For access to all the features of Hoomo, you need to confirm your eamil address first.</p>
    <p>By clicking on below link, we will send you an email with a code, and by inserting this code in the new window, your email adress will be confirmed.</p>
    <%= link_to 'Click here to confirm your email adress', users_email_confirm_path %>
</div>

back/app/views/users/edit.erb
<div class='container mt-3' style='width: 35rem' >
    <h2>Edit Your Account Info:</h2>
    <%= form_for @user,method: :patch, class:'mt-5' do |f| %>
        <div class='mt-3'>
            <%= f.label :first_name, "First Name:", class:'form-label' %>
            <%= f.text_field :first_name, class:'form-control', placeholder:'Your Name' %>
        </div>
        <div class='mt-2'>
            <%= f.label :last_name, 'Last Name:', class:'form-label' %>
            <%= f.text_field :last_name, class:'form-control', placeholder:'Your Last Name' %>
        </div>
        <div class='mt-2'>
            <%= f.label :email, 'Email', class:'form-label' %>
            <%= f.email_field :email, class:'form-control', placeholder:'Ente Your Email' %>
        </div>
        <%= f.submit 'Confirm', class:'btn btn-success mt-3' %>
    <% end %>
</div>

back/app/views/users/new.erb
<div class='container mt-3' style='width: 35rem' >
    <h2>Sign Up</h2>
    <%= form_for @user, class:'mt-5' do |f| %>
    <div class='mt-3'>
        <%= f.label :first_name, "First Name:", class:'form-label' %>
        <%= f.text_field :first_name, class:'form-control', placeholder:'Your Name', required: true %>
    </div>
    <div class='mt-2'>
        <%= f.label :last_name, 'Last Name:', class:'form-label' %>
        <%= f.text_field :last_name, class:'form-control', placeholder:'Your Last Name', required: true %>
    </div>
    <div class='mt-2'>
        <%= f.label :email, 'Email', class:'form-label' %>
        <%= f.email_field :email, class:'form-control', placeholder:'Ente Your Email', required: true %>
    </div>
    <% if @user.errors %>
            <% @user.errors.messages[:email].each do |e| %>
                <div>
                    <small class='text-danger'><%= "• #{e}" %></small>
                </div>
            <% end %>
        <% end %>
    <div class='mt-2'>
        <%= f.label :password, 'Password:', class:'form-label' %>
        <%= f.password_field :password, class:'form-control' %>
        <small class='text-secondary'>• Your password should contain at least 8 characters and at least 1 uppercase letter.</small>
        <div id='error_explanation'>
        <ul>
        <% if @user.errors %>
            <% @user.errors.messages[:password].each do |e| %>
                <div>
                    <small class='text-danger'><%= "• #{e}" %></small>
                </div>
            <% end %>
        <% end %>
        </ul>
    </div>
    <div class='mt-2'>
        <%= f.label :password_confirmation, 'Repeat Your Password:', class:'form-label' %>
        <%= f.password_field :password_confirmation, class:'form-control' %>
    </div>
    <%= f.submit 'Sign Up', class:'btn btn-outline-success mt-3' %>
    <% end %>
</div>

back/app/views/users/reconfirm.erb
<div class='container mt-4' style='width:45rem'>
    <h2>Email Confirmation:</h2>
    <p>In this section, we have sent an email to "<%= current_user.email %>" email address, for finalizing your account creation, you need to enter the CONFIRMATION code in the below form:</p>
    <%= form_tag users_email_confirm_path do %>
        <div>
            <%= label_tag :confirm, "Code:", class:'form-label' %>
            <%= text_field_tag :confirm, nil, class:'form-control', required: true %>
        </div>
        <%= submit_tag "Submit", class:'btn btn-primary mt-3' %>
    <% end %>
    <h4 class="mt-5">You havn't received any code in your email address, click <%= link_to "here", users_email_confirm_path %> to resent the code.</h4>
</div>