back/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  namespace :api do
    namespace :v1 do
      resources :sessions, only: [:create]
      delete 'sessions' => 'sessions#destroy'
      resources :users, only: [:create]
    end
  end

  root "welcome#welcome"

  resources :users, except: [:show]
  get "users/confirming" => 'users#confirming', as: 'send'
  get 'users/email_confirm' => 'users#confirm'
  post "users/email_confirm" => 'users#email_confirm'
  get 'users/reconfirm' => 'users#reconfirm'
  
  resources :search, only: [:create]
  
  get "/session/new" => 'sessions#new'
  post "/session" => 'sessions#create'
  delete '/session' => 'sessions#destroy'
  
  resources :car_profiles do
    
    resources :comments, only: [:create, :destroy] do
      resources :likes, only: [:create, :destroy]
    end
    
    resources :favorites, only: [:index, :create, :destroy]
  end

  resources :welcome, only: [:welcome, :index]

  resources :accounts,  only: [:show]

end

back/app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

    def show
        @user = User.find_by_id params[:id]
    end

end

back/app/helpers/accounts_helper.rb
module AccountsHelper
end

back/app/views/accounts/show.erb
<div class='container' style="width:40rem">
    <h2><%= @user.full_name.capitalize.truncate(30) %>'s Account detail:</h2>
    <ul class="list-group">
        <li class="list-group-item">First Name: <%= @user.first_name %></li>
        <li class="list-group-item">Last Name: <%= @user.last_name %></li>
        <li class="list-group-item">Email Address: <%= @user.email %></li>
        <li class="list-group-item">Your Account has been created at:  <%= @user.created_at.to_formatted_s(:long) %>.</li>
        <li class="list-group-item">Listed Items: <%= @user.CarProfiles.count %></li>
    </ul>
    <div class="d-flex justify-content-between mt-3">
        <%= button_to "Favorited List", car_profile_favorites_path(@user), method: :get, class:'btn btn-primary' %>
        <%= button_to "Edit Account", edit_user_path(@user), class:'btn btn-warning', method: :get %>
        <%= button_to "Delete Account", user_path(@user), method: :delete, class:'btn btn-danger' %>
    </div>
    <div>
    <% if @user.CarProfiles.present? %>
        <h2 class='mt-3'>Listed Items:</h2>
        <% @user.CarProfiles.each do |p| %>
                <div class='card w-70 mt-3' style='width:30rem'>
                    <% if p.image.present? %>
                        <%= image_tag p.image,alt: 'No Image', class:'p-3' %>
                    <% else %>
                        <%= image_tag "no_image.jpg", style:'width:17rem' %>
                    <% end %>
                    <div class="card-body">
                        <p class="card-text">Descriptions: <%= p.content %></p>
                        <p class="card-text">Model: <%= p.model.capitalize %></p>
                        <p class="card-text">Year: <%= p.year %></p>
                        <p class="card-text">Mileage: <%= p.mileage %> km</p>
                        <p class="card-text">Location: <%= p.location %></p>
                        <p class="card-text">Price: <%= p.price %>$ per day</p>
                    </div>
                    <div class='d-flex justify-content-between'>
                        <%= button_to "Edit", edit_car_profile_path(p), class:'btn btn-outline-warning m-3', method: :get %>
                        <%= button_to "Delete", car_profile_path(p), class:'btn btn-outline-danger m-3', method: :delete %>
                    </div>
                </div>
        <% end %>
    <% end %>
    </div>
</div>